### ISSUE TITLE
Not building on linux

### ISSUE THREAD

**Issue by kirill-berezin-ringcentral** [zbjornson/bson-to-json#1]
I've tried several options, but keep running into this issue:

```
> bson-to-json@1.0.0 install /app/node_modules/bson-to-json
> node-gyp rebuild || exit 0

gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.11.3 | linux | x64
gyp http GET https://nodejs.org/download/release/v8.11.3/node-v8.11.3-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v8.11.3/node-v8.11.3-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v8.11.3/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v8.11.3/SHASUMS256.txt
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/app/node_modules/bson-to-json/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/8.11.3/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/8.11.3',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.node-gyp/8.11.3/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/app/node_modules/bson-to-json',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/app/node_modules/bson-to-json/build'
  CC(target) Release/obj.target/nothing/../node-addon-api/src/nothing.o
  AR(target) Release/obj.target/../node-addon-api/src/nothing.a
  COPY Release/nothing.a
  CXX(target) Release/obj.target/bsonToJson/src/bson-to-json.o
../src/bson-to-json.cc:102:11: warning: missing terminating ' character
  102 |  if (v < 1'000) return 4;
      |           ^
../src/bson-to-json.cc:102:11: error: missing terminating ' character
  102 |  if (v < 1'000) return 4;
      |           ^~~~~~~~~~~~~~~
../src/bson-to-json.cc:103:12: warning: missing terminating ' character
  103 |  if (v < 10'000) return 5;
      |            ^
../src/bson-to-json.cc:103:12: error: missing terminating ' character
  103 |  if (v < 10'000) return 5;
      |            ^~~~~~~~~~~~~~~
../src/bson-to-json.cc:104:13: warning: missing terminating ' character
  104 |  if (v < 100'000) return 6;
      |             ^
../src/bson-to-json.cc:104:13: error: missing terminating ' character
  104 |  if (v < 100'000) return 6;
      |             ^~~~~~~~~~~~~~~
../src/bson-to-json.cc:105:11: warning: multi-character character constant [-Wmultichar]
  105 |  if (v < 1'000'000) return 7;
      |           ^~~~~
../src/bson-to-json.cc:106:12: warning: multi-character character constant [-Wmultichar]
  106 |  if (v < 10'000'000) return 8;
      |            ^~~~~
../src/bson-to-json.cc:107:13: warning: multi-character character constant [-Wmultichar]
  107 |  if (v < 100'000'000) return 9;
      |             ^~~~~
../src/bson-to-json.cc:108:11: warning: multi-character character constant [-Wmultichar]
  108 |  if (v < 1'000'000'000) return 10;
      |           ^~~~~
../src/bson-to-json.cc:108:19: warning: missing terminating ' character
  108 |  if (v < 1'000'000'000) return 10;
      |                   ^
../src/bson-to-json.cc:108:19: error: missing terminating ' character
  108 |  if (v < 1'000'000'000) return 10;
      |                   ^~~~~~~~~~~~~~~~
In file included from ../src/bson-to-json.cc:12:
../src/fast_itoa.h:46:44: warning: variable templates only available with '-std=c++14' or '-std=gnu++14'
   46 | template<typename T> constexpr std::size_t INT_BUF_DIGS = 0;
      |                                            ^~~~~~~~~~~~
../src/fast_itoa.h:47:34: warning: variable templates only available with '-std=c++14' or '-std=gnu++14'
   47 | template<> constexpr std::size_t INT_BUF_DIGS<std::int32_t> = 11;
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~
../src/fast_itoa.h:48:34: warning: variable templates only available with '-std=c++14' or '-std=gnu++14'
   48 | template<> constexpr std::size_t INT_BUF_DIGS<std::int64_t> = 20;
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~
../src/bson-to-json.cc: In function 'constexpr std::size_t nDigits(int32_t)':
../src/bson-to-json.cc:102:11: error: expected ')' before 'if'
  102 |  if (v < 1'000) return 4;
      |     ~     ^
      |           )
  103 |  if (v < 10'000) return 5;
      |  ~~        
../src/bson-to-json.cc:105:29: warning: suggest braces around empty body in an 'if' statement [-Wempty-body]
  105 |  if (v < 1'000'000) return 7;
      |                             ^
../src/bson-to-json.cc:106:12: error: expected ')' before '\x303030'
  106 |  if (v < 10'000'000) return 8;
      |     ~      ^~~~~
      |            )
../src/bson-to-json.cc:107:13: error: expected ')' before '\x303030'
  107 |  if (v < 100'000'000) return 9;
      |     ~       ^~~~~
      |             )
../src/bson-to-json.cc:108:6: warning: init-statement in selection statements only available with '-std=c++17' or '-std=gnu++17'
  108 |  if (v < 1'000'000'000) return 10;
      |      ^
../src/bson-to-json.cc:108:11: error: expected ';' before '\x303030'
  108 |  if (v < 1'000'000'000) return 10;
      |           ^~~~~
      |           ;
../src/bson-to-json.cc:108:8: warning: statement has no effect [-Wunused-value]
  108 |  if (v < 1'000'000'000) return 10;
      |      ~~^~~
../src/bson-to-json.cc:110:1: error: expected primary-expression before '}' token
  110 | }
      | ^
../src/bson-to-json.cc:109:12: error: expected ')' before '}' token
  109 |  return 11;
      |            ^
      |            )
  110 | }
      | ~           
../src/bson-to-json.cc:108:5: note: to match this '('
  108 |  if (v < 1'000'000'000) return 10;
      |     ^
../src/bson-to-json.cc:110:1: error: expected primary-expression before '}' token
  110 | }
      | ^
../src/bson-to-json.cc:110:1: error: body of 'constexpr' function 'constexpr std::size_t nDigits(int32_t)' not a return-statement
../src/bson-to-json.cc:110:1: warning: control reaches end of non-void function [-Wreturn-type]
make: *** [Release/obj.target/bsonToJson/src/bson-to-json.o] Error 1
make: Leaving directory `/app/node_modules/bson-to-json/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 5.4.23-1-MANJARO
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /app/node_modules/bson-to-json
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm info lifecycle long@4.0.0~postinstall: long@4.0.0
npm info lifecycle node-addon-api@2.0.0~postinstall: node-addon-api@2.0.0
npm info lifecycle bson-to-json@1.0.0~postinstall: bson-to-json@1.0.0
npm WARN saveError ENOENT: no such file or directory, open '/app/package.json'
npm info lifecycle undefined~preshrinkwrap: undefined
npm info lifecycle undefined~shrinkwrap: undefined
npm notice created a lockfile as package-lock.json. You should commit this file.
npm info lifecycle undefined~postshrinkwrap: undefined
npm WARN enoent ENOENT: no such file or directory, open '/app/package.json'
npm WARN app No description
npm WARN app No repository field.
npm WARN app No README data
npm WARN app No license field.
```

Here the code to reproduce:

```
FROM centos:7
RUN yum install git make gcc-c++ lbzip2 -y
ENV GCC_VERSION=9.2.0
RUN wget https://ftp.gnu.org/gnu/gcc/gcc-${GCC_VERSION}/gcc-${GCC_VERSION}.tar.gz
RUN tar xzvf gcc-${GCC_VERSION}.tar.gz
RUN mkdir obj.gcc-${GCC_VERSION}
WORKDIR gcc-${GCC_VERSION}
RUN ./contrib/download_prerequisites
WORKDIR ../obj.gcc-${GCC_VERSION}
RUN ../gcc-${GCC_VERSION}/configure --disable-multilib --enable-languages=c,c++
RUN make -j $(nproc)
#RUN yum install devtoolset-9-toolchain && scl enable devtoolset-9 bash
RUN yum install libstdc++ -y
RUN make install
RUN g++ -v

WORKDIR /app
RUN npm install -g node-gyp
RUN npm install zbjornson/bson-to-json
```

Probably C++17 flags required for G++ as well.

**Comment by zbjornson** [comment]
Thanks for the clear repro steps. I'm running behind on open-source stuff but hope to get this fixed tonight or this weekend. (You can try adding `"-std=c++17"` to `cflags` on line 23 of `binding.gyp` if you're set up to try fixes locally.)

**Comment by zbjornson** [comment]
This only affects Node.js v8, which is EOL. I've changed the build config so it works with v8 in the above commit.

**Comment by Enelar** [comment]
Confirmed, builds successfully with all latest binaries v9 - v13.
Maybe we could add
`{ "engines" : { "node" : ">=9" } }`
In package.json

**Comment by zbjornson** [comment]
I'll add `engines`, good idea. The latest version (d2782a5) should build with v8 also though.

**Comment by Enelar** [comment]
Confirmed, 8.17.0 - works. Thanks!
